FROM node:20-alpine

# Enable and prepare pnpm
RUN corepack enable && corepack prepare pnpm@9.0.0 --activate

# Set working directory
WORKDIR /app
# Copy dependency and config files first (better for Docker cache)
COPY package.json .
COPY pnpm-lock.yaml .
COPY turbo.json .
COPY pnpm-workspace.yaml .
# Copy the rest of the project
COPY . .
# Install dependencies
RUN pnpm install
# Generate Prisma client 
RUN pnpm run db:generate
# Build the project
RUN pnpm run build
# Start the app
CMD [ "pnpm","run","start_web" ]

